<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="7" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22003" started-at="2018-08-17T18:57:19Z" finished-at="2018-08-17T18:57:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22003" started-at="2018-08-17T18:57:19Z" finished-at="2018-08-17T18:57:41Z">
      <class name="com.revature.testng.TabBarTests">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.revature.testng.TabBarTests@647e447]" name="beforeTest" is-config="true" duration-ms="11541" started-at="2018-08-17T18:57:19Z" finished-at="2018-08-17T18:57:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="testBatchesTab()[pri:0, instance:com.revature.testng.TabBarTests@647e447]" name="testBatchesTab" duration-ms="2131" started-at="2018-08-17T18:57:30Z" finished-at="2018-08-17T18:57:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBatchesTab -->
        <test-method status="PASS" signature="testCurriculaTab()[pri:0, instance:com.revature.testng.TabBarTests@647e447]" name="testCurriculaTab" duration-ms="708" started-at="2018-08-17T18:57:32Z" finished-at="2018-08-17T18:57:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCurriculaTab -->
        <test-method status="PASS" signature="testLocationsTab()[pri:0, instance:com.revature.testng.TabBarTests@647e447]" name="testLocationsTab" duration-ms="148" started-at="2018-08-17T18:57:33Z" finished-at="2018-08-17T18:57:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLocationsTab -->
        <test-method status="PASS" signature="testOverviewTab()[pri:0, instance:com.revature.testng.TabBarTests@647e447]" name="testOverviewTab" duration-ms="2379" started-at="2018-08-17T18:57:33Z" finished-at="2018-08-17T18:57:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOverviewTab -->
        <test-method status="FAIL" signature="testReportsTab()[pri:0, instance:com.revature.testng.TabBarTests@647e447]" name="testReportsTab" duration-ms="440" started-at="2018-08-17T18:57:36Z" finished-at="2018-08-17T18:57:36Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at com.revature.testng.TabBarTests.testReportsTab(TabBarTests.java:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testReportsTab -->
        <test-method status="FAIL" signature="testSettingsTab()[pri:0, instance:com.revature.testng.TabBarTests@647e447]" name="testSettingsTab" duration-ms="3510" started-at="2018-08-17T18:57:36Z" finished-at="2018-08-17T18:57:39Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at com.revature.testng.TabBarTests.testSettingsTab(TabBarTests.java:100)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSettingsTab -->
        <test-method status="PASS" signature="testTrainersTab()[pri:0, instance:com.revature.testng.TabBarTests@647e447]" name="testTrainersTab" duration-ms="313" started-at="2018-08-17T18:57:39Z" finished-at="2018-08-17T18:57:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTrainersTab -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.revature.testng.TabBarTests@647e447]" name="afterTest" is-config="true" duration-ms="792" started-at="2018-08-17T18:57:40Z" finished-at="2018-08-17T18:57:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.revature.testng.TabBarTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
