<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="22" hostname="2CE4250J62" name="com.revature.testng.Assignforce_Testing_KW" tests="24" failures="0" timestamp="20 Aug 2018 07:33:25 GMT" time="3.250" errors="2">
  <testcase name="adminIterateThroughRoom" time="3.218" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminIterateThroughRoom -->
  <testcase name="adminCreateNewBatchAndCancel10" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminCreateNewBatchAndCancel10 -->
  <testcase name="adminCreateNewBatchAndCancel" time="0.024" classname="com.revature.testng.Assignforce_Testing_KW">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.revature.testng.Assignforce_Testing_KW.adminCreateNewBatchAndCancel(Assignforce_Testing_KW.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- adminCreateNewBatchAndCancel -->
  <testcase name="adminCreateNewBatchAndCancel2" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminCreateNewBatchAndCancel2 -->
  <testcase name="adminCreateNewBatchAndCancel9" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminCreateNewBatchAndCancel9 -->
  <testcase name="adminCreateNewBatchAndSubmit" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminCreateNewBatchAndSubmit -->
  <testcase name="adminEditMultipleBatch" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminEditMultipleBatch -->
  <testcase name="adminIterateThroughCotrainers" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminIterateThroughCotrainers -->
  <testcase name="adminIterateThroughSkillsList" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminIterateThroughSkillsList -->
  <testcase name="adminCreateNewBatchAndCancel3" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminCreateNewBatchAndCancel3 -->
  <testcase name="adminCreateNewBatchAndCancel5" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminCreateNewBatchAndCancel5 -->
  <testcase name="adminEditSingleBatch" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminEditSingleBatch -->
  <testcase name="logoutAndCloseDriver" time="0.008" classname="com.revature.testng.Assignforce_Testing_KW">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.revature.testng.Assignforce_Testing_KW.logoutAndCloseDriver(Assignforce_Testing_KW.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- logoutAndCloseDriver -->
  <testcase name="adminIterateThroughTrainers" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminIterateThroughTrainers -->
  <testcase name="adminCreateNewBatchAndCancel6" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminCreateNewBatchAndCancel6 -->
  <testcase name="adminCreateNewBatchAndCancel8" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminCreateNewBatchAndCancel8 -->
  <testcase name="adminIterateThroughBatchCoreList" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminIterateThroughBatchCoreList -->
  <testcase name="adminIterateThroughBatchCoreUntilMemoryFault" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminIterateThroughBatchCoreUntilMemoryFault -->
  <testcase name="adminIterateThroughLocations" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminIterateThroughLocations -->
  <testcase name="testUserLogin" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- testUserLogin -->
  <testcase name="adminCreateNewBatchAndCancel4" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminCreateNewBatchAndCancel4 -->
  <testcase name="testAdminLogin" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- testAdminLogin -->
  <testcase name="adminIterateThroughBuildling" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminIterateThroughBuildling -->
  <testcase name="adminCreateNewBatchAndCancel7" time="0.000" classname="com.revature.testng.Assignforce_Testing_KW">
    <skipped/>
  </testcase> <!-- adminCreateNewBatchAndCancel7 -->
</testsuite> <!-- com.revature.testng.Assignforce_Testing_KW -->
